Add support Events (CS1)
checkout/checkout-sdk-python pull request #49
Opened 2022-04-25 03:28 UTC by Armando-Ibarra

2022-04-25 08:10 UTC, rsaestrela requested changes

2022-04-25 08:10 UTC, rsaestrela commented on tests/events/events_client_test.py
> +class TestWebhooksClient:
This should be `TestEventsClient`

2022-04-25 08:11 UTC, rsaestrela commented
Please merge #48 so we can then point this one to master and finish the review. Everything looks fine!

2022-04-25 12:28 UTC, Armando-Ibarra commented on tests/events/events_client_test.py
> +class TestWebhooksClient:
Yeah, copy paste thing, sorry and fixed

2022-04-26 09:04 UTC, rsaestrela approved these changes

2022-04-26 09:04 UTC, rsaestrela commented on tests/events/events_integration_test.py
> +def test_should_retrieve_default_event_types(default_api):
Name should be ` test_should_retrieve_event_types` since this test is testing different scenarios (default, v1, v2, etc).

2022-04-27 03:09 UTC, merged